### ISSUE TITLE
exited with code 0

### ISSUE THREAD

**Issue by rmarasigan** [nouchka/docker-sqlite3#3]
Hello, good day. why does it always gives me `exited with code 0`? Like every minute, its printing `sqlite-db exited with code 0`. Here's my docker-compose.yml

```
database:
    image: nouchka/sqlite3:latest
    container_name: sqlite-db
    volumes:
      - sqlite-db:/var/lib/sqlite
    restart: unless-stopped
```

I do have another service that is for my Go application
